### ISSUE TITLE
peer to peer storage

### ISSUE THREAD

**Issue by haiderali3071** [Cyber-Monkeys/StorIt#24]
Hi, actually I am doing a project in which a module is that if a user has some free storage on his computer then he can contribute this storage to p2p storage network and can earn some reward more likely a cryptocurrency. Can you give me a starting point like how can I build this p2p storage network?
I asked you because you have already done a related project so may you can guide me better.

**Comment by humaidk2** [comment]
Hi,

First off, let me just tell you that there's already a p2p storage crypto project built by many experts, called [storj](https://www.storj.io/). They also have their own cryptocurrency, [tardigrade](https://www.coingecko.com/en/coins/tardigrades-finance)

Secondly, the project is really hard to pull off and requires a lot of work, sweat, and tears. Also there's not much to show for it,  most of the work is in the backend, so all users get to see is this file upload/download ui.

That being said, I think it's an awesome project and you'll get to learn a ton. As long as you break everything down to small steps and stick with it, you  should be able to complete the project.

For p2p networks, the starting point would be to look into the NAT and how to setup a server that bypasses the nat. The proper way of setting up a reliable network is to setup port forwarding. Check out Storj [docs](https://docs.storj.io/node/dependencies/port-forwarding).

The next problem you'll should solve is security. You'll need to ensure that files are not accessible in transit or on the storage node.

Also, you'll need to keep track of files and where they're stored.

The last big challenge that you'll have is setting up a cryptocurrency(prob around a blockchain) and managing users transactions.

The biggest non-technical challenge that your project will face is attracting users who provide storage, especially at the beginning. What do they get from providing storage?

That's all the info, I can give you.

Good Luck.
